
#define MAX_APP_NAME 100
#define MAX_USERNAME 200
#define MAX_LEN_NUMBER_ROOM 10

#define MAX_CLIENTS 2000


#define SLEEP_THREAD_USER_READ_SOCK 10
#define SLEEP_THREAD_ACCEPT_USERS 10

#define WAITING_BLOCK_MS 10
#define MAX_DATA_RECEVIED_BY_PACKET 65000

#define BYTES_LEN_HEADER 2

#define MAX_DATA_RECEVIED_BY_PACKET 65000

#define DEBUG
